### ISSUE TITLE
[BUG]: container:  name: hlm-selenium-webview can't be resolved

### ISSUE THREAD

**Issue by CraigRichards** [healenium/healenium-proxy#6]
### Describe the bug

I was testing out the DotNet project and found it was not working. After looking up the logs I ran the Proxy locally and 'hlm-selenium-webview' can't be resolved.

Hope this helps

### How to reproduce the issue

```shell
Run Docker-compose from .Net Ifra
Execute the test

Look in Proxy logs for DNS Resolution Failure - hlm-selenium-webview
```

### Logs appeared during using Healenium

```shell
As above
```

### Healenium Backend version

3.2.0

### Selenium version

3.14.1.0

### Platform

.Net / Java

**Comment by ElenaStepuro** [comment]
Reupdated `docker-compose.yaml` file in .NET solution example
